// Recorder — captures Playwright actions and generates ai() code

import type { Page } from '@playwright/test'

export interface RecordedStep {
  instruction: string
  action: string
  selector: string
  timestamp: number
}

export interface RecordedSession {
  steps: RecordedStep[]
  startUrl: string
  duration: number
}

export class AiRecorder {
  private steps: RecordedStep[] = []
  private startTime = 0
  private startUrl = ''

  /**
   * Start recording actions on a Playwright page.
   * Attaches listeners to capture page events (clicks, navigation, etc.)
   */
  start(page: Page): void {
    this.steps = []
    this.startTime = Date.now()
    this.startUrl = page.url()

    // Reset on navigation
    page.on('framenavigated', () => {
      this.steps = []
    })
  }

  /**
   * Record a single action with a natural-language description.
   */
  addStep(instruction: string, action = 'action', selector = ''): void {
    this.steps.push({
      instruction,
      action,
      selector,
      timestamp: Date.now() - this.startTime,
    })
  }

  /**
   * Stop recording and return the session data.
   */
  stop(): RecordedSession {
    return {
      steps: this.steps,
      startUrl: this.startUrl,
      duration: Date.now() - this.startTime,
    }
  }

  /**
   * Generate TypeScript test code from the recorded session.
   */
  generateCode(session: RecordedSession, testName = 'Recorded Session'): string {
    const lines: string[] = [
      `// Auto-generated by playwright-ai-step recorder`,
      `// Session: ${session.startUrl}`,
      `// Duration: ${Math.round(session.duration / 1000)}s`,
      `// Steps: ${session.steps.length}`,
      ``,
      `import { test } from 'playwright-ai-step'`,
      ``,
      `test('${testName}', async ({ page, ai }) => {`,
    ]

    for (const step of session.steps) {
      const escaped = step.instruction.replace(/"/g, '\\"')
      lines.push(`  await ai("${escaped}", { page })`)
    }

    lines.push('})')
    return lines.join('\n')
  }
}

// ─── CLI recorder ──────────────────────────────────────────────────────

export interface RecorderOptions {
  outputPath?: string
  testName?: string
}

export async function runRecorderCLI(url: string, options: RecorderOptions = {}): Promise<void> {
  const { chromium } = await import('playwright')
  const recorder = new AiRecorder()

  const browser = await chromium.launch({ headless: true })
  const context = await browser.newContext()
  const page = await context.newPage()

  console.log(`🎬 Recording: ${url}`)
  console.log('  Interact with the page. Press Ctrl+C to stop.\n')

  recorder.start(page)
  await page.goto(url)

  await new Promise<void>((resolve) => {
    process.on('SIGINT', () => {
      console.log('\n⏹  Stopping...')
      resolve()
    })
  })

  const session = recorder.stop()
  const code = recorder.generateCode(session, options.testName ?? 'recorded-test')

  if (options.outputPath) {
    const { writeFileSync } = await import('fs')
    writeFileSync(options.outputPath, code)
    console.log(`✅ Written to: ${options.outputPath}`)
  } else {
    console.log('\n--- Generated Test ---')
    console.log(code)
  }

  await browser.close()
}