// Sitemap-based test generation

export interface SitemapUrl {
  url: string
  changefreq?: string
  priority?: number
  lastmod?: string
}

export type SitemapTestType = 'basic' | 'form' | 'navigation'

export interface GenerateSitemapTestsOptions {
  testType: SitemapTestType
  baseUrl: string
  outputPath?: string
  testName?: string
}

// ─── XML Parser ─────────────────────────────────────────────────────────

interface XmlNode {
  tag: string
  attrs: Record<string, string>
  children: XmlNode[]
  text: string
}

function parseXmlSimple(xml: string): XmlNode[] {
  const result: XmlNode[] = []
  let i = 0

  function skipWhitespace() {
    while (i < xml.length && /\s/.test(xml[i])) i++
  }

  function parseNode(): XmlNode | null {
    skipWhitespace()
    if (i >= xml.length || xml[i] !== '<') return null

    i++ // skip <
    if (xml[i] === '/') { i++; /* skip closing */ }
    const nameStart = i
    while (i < xml.length && !/[\s/>]/.test(xml[i])) i++
    const name = xml.slice(nameStart, i).toLowerCase()

    const attrs: Record<string, string> = {}
    skipWhitespace()
    while (i < xml.length && xml[i] !== '>' && xml[i] !== '/') {
      const attrNameStart = i
      while (i < xml.length && /[\s=]/.test(xml[i])) i++
      const attrName = xml.slice(attrNameStart, i).trim()
      if (attrName && xml[i] === '=') {
        i++
        skipWhitespace()
        const quote = xml[i]
        if (quote === '"' || quote === "'") {
          i++
          const valStart = i
          while (i < xml.length && xml[i] !== quote) i++
          attrs[attrName] = xml.slice(valStart, i)
          if (xml[i] === quote) i++
        }
      }
      skipWhitespace()
    }
    if (xml[i] === '/') i++
    i++ // skip >

    const children: XmlNode[] = []
    const textParts: string[] = []

    while (i < xml.length) {
      skipWhitespace()
      if (xml.slice(i, i + 2) === '</') {
        i += 2
        while (i < xml.length && xml[i] !== '>') i++
        i++
        break
      }
      if (xml[i] === '<') {
        const child = parseNode()
        if (child) children.push(child)
      } else {
        textParts.push(xml[i])
        i++
      }
    }

    return { tag: name, attrs, children, text: textParts.join('').trim() }
  }

  while (i < xml.length) {
    skipWhitespace()
    if (i < xml.length && xml[i] === '<') {
      const node = parseNode()
      if (node) result.push(node)
    } else {
      i++
    }
  }

  return result
}

function extractLocText(node: XmlNode): string {
  if (node.tag === 'loc') return node.text
  for (const child of node.children) {
    const found = extractLocText(child)
    if (found) return found
  }
  return ''
}

// ─── Sitemap parser ─────────────────────────────────────────────────────

export async function parseSitemap(sitemapUrl: string): Promise<SitemapUrl[]> {
  const response = await fetch(sitemapUrl)
  if (!response.ok) throw new Error(`Failed to fetch sitemap: ${response.status}`)

  const xml = await response.text()
  const nodes = parseXmlSimple(xml)

  const urls: SitemapUrl[] = []

  function processNodes(items: XmlNode[]) {
    for (const item of items) {
      if (item.tag === 'url') {
        const url = extractLocText(item)
        if (url) {
          urls.push({
            url,
            changefreq: item.children.find(c => c.tag === 'changefreq')?.text?.trim(),
            priority: item.children.find(c => c.tag === 'priority')?.text?.trim()
              ? parseFloat(item.children.find(c => c.tag === 'priority')!.text)
              : undefined,
            lastmod: item.children.find(c => c.tag === 'lastmod')?.text?.trim(),
          })
        }
      }
      if (item.children?.length) {
        processNodes(item.children)
      }
    }
  }

  processNodes(nodes)
  return urls
}

// ─── Test generator ────────────────────────────────────────────────────

export async function generateSitemapTests(
  sitemapUrl: string,
  options: GenerateSitemapTestsOptions,
): Promise<string> {
  const urls = await parseSitemap(sitemapUrl)

  if (urls.length > 50) {
    console.warn(`[playwright-ai-step] Sitemap has ${urls.length} URLs — capped at 50. Pass a filtered subset if needed.`)
  }

  const testType = options.testType
  const baseUrl = options.baseUrl

  const lines: string[] = [
    '// Auto-generated by playwright-ai-step (sitemap generator)',
    `// Source: ${sitemapUrl}`,
    `// Test type: ${testType}`,
    `// Generated: ${new Date().toISOString()}`,
    '',
    "import { test, expect } from '@playwright/test'",
    '',
  ]

  const count = Math.min(urls.length, 50)

  for (let i = 0; i < count; i++) {
    const entry = urls[i]
    const relativePath = entry.url.replace(baseUrl, '').replace(/^\//, '') || 'index'
    const safeName = relativePath.replace(/[^a-zA-Z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '')

    lines.push(`test('${safeName}', async ({ page }) => {`)

    if (testType === 'basic') {
      lines.push(`  await page.goto('${entry.url}')`)
      lines.push(`  const title = await page.title()`)
      lines.push(`  expect(title).toBeTruthy()`)
    } else if (testType === 'navigation') {
      lines.push(`  await page.goto('${entry.url}')`)
      lines.push(`  const errors: string[] = []`)
      lines.push(`  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })`)
      lines.push(`  await page.waitForTimeout(1000)`)
      lines.push(`  expect(errors.length).toBe(0)`)
      lines.push(`  const linkCount = await page.locator('a[href]').count()`)
      lines.push(`  expect(linkCount).toBeGreaterThan(0)`)
    } else {
      lines.push(`  await page.goto('${entry.url}')`)
      lines.push(`  const formCount = await page.locator('form').count()`)
      lines.push(`  expect(formCount).toBeGreaterThanOrEqual(0)`)
    }

    lines.push('})')
    lines.push('')
  }

  lines.push(`// Total URLs: ${urls.length}, shown: ${count}`)
  return lines.join('\n')
}

export async function generateSitemapTestsToFile(
  sitemapUrl: string,
  options: GenerateSitemapTestsOptions,
): Promise<{ filePath: string; urlCount: number }> {
  const content = await generateSitemapTests(sitemapUrl, options)
  const { writeFileSync } = await import('fs')
  const outputPath = options.outputPath ?? `tests/sitemap-${options.testType}-${Date.now()}.test.ts`
  writeFileSync(outputPath, content)
  // Extract count from the comment already present in generated content — avoids a second network request
  const match = content.match(/\/\/ Total URLs: \d+, shown: (\d+)/)
  const urlCount = match ? parseInt(match[1], 10) : 0
  return { filePath: outputPath, urlCount }
}