// Test Generator — generate Playwright test files from natural language specs

import { resolveLLMConfig } from './config'

export interface GenerateTestOptions {
  baseUrl: string
  model?: string
  includeComments?: boolean
  testName?: string
}

const PLANNER_PROMPT = `You are a Playwright test planning expert.
Given a user's natural language description of a test scenario, break it down into Playwright test steps.

Return ONLY a JSON array of steps. Each step is:
{
  "instruction": "what the user does in plain English",
  "expectedUrl": "regex pattern for URL (or null)",
  "waitForSelector": "CSS selector (or null)",
  "type": "action" | "assert" | "query"
}

Rules:
- Break into atomic steps
- For forms: separate fill from submit
- Include at least one assert per test
- 1-8 steps total, prefer fewer meaningful steps
- Return ONLY the JSON array, no markdown, no explanation.`

function buildSpecPrompt(spec: string): string {
  return `User test description: "${spec}"

Break this down into test steps as a JSON array.`
}

function parseSteps(raw: string): { instruction?: string; expectedUrl?: string; waitForSelector?: string; type?: string }[] {
  let jsonStr = raw.trim()
  if (jsonStr.startsWith('```')) {
    const fenceEnd = jsonStr.indexOf('\n')
    jsonStr = jsonStr.slice(fenceEnd + 1)
    const fenceClose = jsonStr.lastIndexOf('```')
    if (fenceClose > 0) jsonStr = jsonStr.slice(0, fenceClose)
  }
  jsonStr = jsonStr.trim()

  try {
    const parsed = JSON.parse(jsonStr)
    if (Array.isArray(parsed)) return parsed
  } catch { /* fall through */ }

  const match = jsonStr.match(/\[\s*\{[\s\S]*\}\s*\]/)
  if (match) {
    try { return JSON.parse(match[0]) } catch { /* fall through */ }
  }
  return []
}

function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/`/g, '\\`')
}

export async function generateTest(
  spec: string,
  options: GenerateTestOptions,
): Promise<string> {
  const config = resolveLLMConfig()
  const { default: OpenAI } = await import('openai')
  const client = new OpenAI({ apiKey: config.apiKey, baseURL: config.baseUrl, timeout: config.timeoutMs })

  const response = await client.chat.completions.create({
    model: config.model,
    messages: [
      { role: 'system', content: PLANNER_PROMPT },
      { role: 'user', content: buildSpecPrompt(spec) },
    ],
    max_tokens: 1024,
    temperature: 0.1,
  })

  const content = response.choices[0]?.message?.content ?? '[]'
  const parsedSteps = parseSteps(content)

  const testName = options.testName ?? spec.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '-').toLowerCase()
  const includeComments = options.includeComments !== false

  const lines: string[] = [
    '// Auto-generated by playwright-ai-step',
    `// Spec: ${escapeString(spec)}`,
    `// Generated: ${new Date().toISOString()}`,
    '',
    "import { test, expect } from '@playwright/test'",
    '',
    `test('${escapeString(testName)}', async ({ page }) => {`,
  ]

  if (includeComments) {
    lines.push(`  // Spec: ${escapeString(spec)}`)
  }

  for (let i = 0; i < parsedSteps.length; i++) {
    const step = parsedSteps[i]
    const instruction = escapeString(step.instruction ?? `step ${i + 1}`)

    if (step.type === 'assert') {
      lines.push(`  // assert: ${instruction}`)
      lines.push(`  await expect(page).toHaveTitle(/.+/)  // verify page has title`)
    } else if (step.type === 'query') {
      lines.push(`  // query: ${instruction}`)
      lines.push(`  const _result = await page.title()  // placeholder for query`)
    } else {
      lines.push(`  // ${instruction}`)
      lines.push(`  await page.goto('${options.baseUrl}')`)
      lines.push(`  await page.waitForTimeout(1000)`)
    }
  }

  lines.push('})')
  return lines.join('\n')
}